### Send email using the API
POST http://localhost:3000/mail/send
Content-Type: application/json
x-api-key: testAPIkey3000

{
  "to": "example@example.com",
  "subject": "Test Email",
  "text": "This is a test email sent from my API."
}

### Send invalid email using the API
POST http://localhost:3000/mail/send
Content-Type: application/json
x-api-key: testAPIkey3000

{
  "to": "example@example",
  "subject": "Test Email",
  "text": "This is a test email sent from my API."
}
###
POST http://localhost:3000/mail/send
Content-Type: application/json
x-api-key: testAPIkey3000

{
  "to": "example@example.com'; DROP TABLE users; --",
  "subject": "Test Email",
  "text": "This is a test email sent from my API."
}

###
POST http://localhost:3000/mail/send
Content-Type: application/json
x-api-key: testAPIkey3000

{
  "subject": "Test Email",
  "text": "This is a test email sent from my API."
}
###
POST http://localhost:3000/mail/send
Content-Type: application/json
x-api-key: testAPIkey3000

{
  "to": "invalid-email-address",
  "subject": "Test Email",
  "text": "This is a test email sent from my API."
}